"""Aplicar cambios a Material.

Revision ID: 45a5650dce01
Revises: 3f7140071181
Create Date: 2024-05-18 16:01:37.213123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a5650dce01'
down_revision = '3f7140071181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('synced')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
